### ISSUE TITLE
Incorrect regex

### ISSUE THREAD

**Issue by simensgreen** [maciejhirsz/logos#302] opened 2023-04-24 18:26 UTC
```rust
#[derive(Debug, Logos)]
enum Token {
    #[regex(r"\(.*\)")]
    Unbrace
}

let mut lex = Token::lexer("(any text)"); // matches r"\(.*\)"

let result = lex.next();
assert!(matches!(result, Some(_)));     
assert!(matches!(result, Some(Ok(_)))); // fail
```

logos = "0.13.0"

**Comment by simensgreen** [comment] 2023-04-24 18:36
I have seen many issues about erroneous regular expressions. Why not use a ready-made, well-tested library such as [regex](https://lib.rs/crates/regex)?

**Comment by jeertmans** [comment] 2023-04-25 07:59
Nice catch for this bug!

I think Logos does not directly use the `regex` crate for one important reason: performances.

If you look closely at how Logos is implemented, it uses `regex-syntax` (from which `regex` also depends on) and parses the regex into some intermediate representation. As Logos makes heavily use of optimized look-up tables, it has to "re-implement" a lot of the logic behind regex to make it fit into its model. That's at least how I understand Logos.

**Comment by maciejhirsz** [comment] 2023-04-25 08:02
This is an easy fix, just match for anything that's not a closing paren: `r"\([^)]*\)"`

This is also not a bug per se.

> I have seen many issues about erroneous regular expressions. Why not use a ready-made, well-tested library such as [regex](https://lib.rs/crates/regex)?

So these are related questions. Logos never was, and never will be (see "Phasing out `#[regex]`" in [last release notes](https://github.com/maciejhirsz/logos/releases)) a fully featured regex engine.

Using the `regex` crate would absolutely kill the performance here. That's not throwing shade on `regex`, it's one of the fastest if not the fastest regex implementation on the planet. To use it as a backend for Logos however two things would happen:

1. The whole compiling of the state machine would happen at runtime (it happens at compile time currently). There is some runtime cost to that, though it's amortized by only having to do it once per lexer, however...
2. We would go from looking at each byte of input _at most_ twice (and more often enough it manages with looking at any byte just once), to looking _at least_ N times, where N is the number of token definitions, and at most N * X times, where X is some indefinite number of backtracks any given regex pattern can do. Even if the `regex` crate was so optimized that it only used one CPU cycle per byte when it looks at it, for a complex enough Lexer you are looking at order of magnitude or more performance loss.

(@jeertmans you replied just as I was typing this :upside_down_face:)

**Closed by maciejhirsz** 2023-04-25 08:02 UTC

**Comment by maciejhirsz** [comment] 2023-04-25 08:09
One last note I'll leave here: might be worth considering throwing a compile error on glob repeat (`.*`) pattern: it will always happily eat the entire input to the end, and I don't know a single scenario where that's actually a useful thing in a lexer.

**Comment by jeertmans** [comment] 2023-04-25 08:26
I feel that it should also be documented somewhere @maciejhirsz, maybe in the future book or in the crate's docs, but I recognize that's not the first time someone falls into the `.*` trap ^^.

A compiler error might also help users!
