### ISSUE TITLE
Common regexes for the Logos Handbook

### ISSUE THREAD

**Issue by maciejhirsz** [maciejhirsz/logos#133] opened 2020-04-25 09:21 UTC
Not to go offtopic in #132, but it's pretty common that someone ends up reinventing a regex for something that can be done better, or has problems finding one that works (#124). This is doubly problematic since Logos doesn't support non-greedy matching ([for good reasons](https://en.wikipedia.org/wiki/ReDoS)). There is a lot of overlap when lexing programming languages on things like:

+ Comments
+ Quoted strings
+ Floating point numbers with scientific notation

I already started noodling on a [book](https://github.com/maciejhirsz/logos/tree/book) to supplement the API docs, and I plan on having a chapter with commonly used regexes so people can look things up quickly. If you can think of something that might be a common use case, please add it in the comments below so it can be included in the book.

**Comment by CAD97** [comment] 2020-04-25 21:42
It's probably worth including an example for lexing (most of?) Rust's lexical structure, because that serves as a common baseline that users of logos probably understand. That said, here's a dump of the regex I've been using for the tokens I think are likely to be more generally reusable:

- line comment (excluding trailing newline): `//[^\n]*`
- line comment (including trailing newline): `//[^\n]*\n?`
- block comment (unnested): `/*(?:[^*]|\*[^/])*\*/`
- identifier ([UAX#31](https://unicode.org/reports/tr31/)): `\p{XID_Start}\p{XID_Continue}*`
- identifier (traditional ASCII): `[_a-zA-Z][_0-9a-zA-Z]*`
- binary integer: `0b_*[01][_01]*`
- octal integer `0o_*[0-7][_0-7]*`
- decimal integer: `[1-9][_1-9]*`
- decimal float: `(?&digits)(?:e(?&digits)|\.(?&digits)(?:e(?&digits))?)`
- string (minimal escapes): `"(?:[^"]|\\")*"`

**Comment by Jezza** [comment] 2020-09-04 14:01
I regret nothing.

```
[+-]?(([0-9][_0-9]*\.([0-9][_0-9]*)?([eE][+-]?([0-9][_0-9]*))?[fFdD]?)|(\.([0-9][_0-9]*)([eE][+-]?([0-9][_0-9]*))?[fFdD]?)|(([0-9][_0-9]*)([eE][+-]?([0-9][_0-9]*))[fFdD]?)|(([0-9][_0-9]*)([eE][+-]?([0-9][_0-9]*))?[fFdD]))
```

This matches floating point java style literals.

So, it'll match stuff like:
```
2.2F
3.5F
.0
.2D
.2F
.2e2
-2e2
```

And reject stuff like:
```
1
.F
```

![image](https://user-images.githubusercontent.com/4224088/92247629-c8069a80-eec7-11ea-87b2-9f8dc1cca3af.png)

**Comment by Jezza** [comment] 2020-09-04 17:22
I found out about subpatterns about 3 hours ago and in that time I cleaned the regexes I use.

```rust
#[logos(subpattern decimal = r"[0-9][_0-9]*")]
#[logos(subpattern hex = r"[0-9a-fA-F][_0-9a-fA-F]*")]
#[logos(subpattern octal = r"[0-7][_0-7]*")]
#[logos(subpattern binary = r"[0-1][_0-1]*")]
#[logos(subpattern exp = r"[eE][+-]?[0-9][_0-9]*")]
enum TokenKind {
	#[regex(r"//.*\n?", logos::skip)]
	#[regex(r"[ \t\n\f]+", logos::skip)]
	#[error]
	Error,

  	#[regex("(?&decimal)")]
	Integer,

	#[regex("0[xX](?&hex)")]
	HexInteger,

	#[regex("0[oO](?&octal)")]
	OctalInteger,

	#[regex("0[bB](?&binary)")]
	BinaryInteger,

	#[regex(r#"[+-]?(((?&decimal)\.(?&decimal)?(?&exp)?[fFdD]?)|(\.(?&decimal)(?&exp)?[fFdD]?)|((?&decimal)(?&exp)[fFdD]?)|((?&decimal)(?&exp)?[fFdD]))"#)]
	Float,

	#[regex(r"0[xX](((?&hex))|((?&hex)\.)|((?&hex)?\.(?&hex)))[pP][+-]?(?&decimal)[fFdD]?")]
	HexFloat,
}
```

This isn't all of the tokens I use, but I feel like a lot of these are very common (With the exception of HexFloat...).

It should be a good starting point for a lot of people wanting to not care about numbers (Specifically floats).

**Comment by HactarCE** [comment] 2021-03-03 06:09
>     * block comment (unnested): `/*(?:[^*]|\*[^/])*\*/`

This regex has a few issues:
- Missing `\` before the first `*`
- Fails to match `/***/`

Here is the version I am using: `/\*([^*]|\*+[^*/])*\*+/` ([test cases](https://regex101.com/r/Fuqfv3/1))

**Comment by Keats** [comment] 2021-05-22 07:50
@HactarCE I'm getting an `[Error]` with that regex if I try to do something as simple as:

```
#[derive(Logos, Debug, PartialEq, Copy, Clone)]
pub(crate) enum CommentLexer {
    #[regex(r"/\*([^*]|\*+[^*/])*\*+/")]
    Comment,
    #[error]
    Error,
}
```
and try to lex  `/* basic */` (or any comment really).
Any idea what's wrong?

**Comment by hypopyon** [comment] 2022-12-09 00:34
&any: `[\s\S]`
String literal: `"(?:[^"\\]|\\&any)*"`
Raw string literal: `r(#*)"(?:(?!\1)|&any)*"\1`

**Comment by edg-l** [comment] 2023-07-06 09:47
> It's probably worth including an example for lexing (most of?) Rust's lexical structure, because that serves as a common baseline that users of logos probably understand. That said, here's a dump of the regex I've been using for the tokens I think are likely to be more generally reusable:
> 
>     * line comment (excluding trailing newline): `//[^\n]*`
> 
>     * line comment (including trailing newline): `//[^\n]*\n?`
> 
>     * block comment (unnested): `/*(?:[^*]|\*[^/])*\*/`
> 
>     * identifier ([UAX#31](https://unicode.org/reports/tr31/)): `\p{XID_Start}\p{XID_Continue}*`
> 
>     * identifier (traditional ASCII): `[_a-zA-Z][_0-9a-zA-Z]*`
> 
>     * binary integer: `0b_*[01][_01]*`
> 
>     * octal integer `0o_*[0-7][_0-7]*`
> 
>     * decimal integer: `[1-9][_1-9]*`
> 
>     * decimal float: `(?&digits)(?:e(?&digits)|\.(?&digits)(?:e(?&digits))?)`
> 
>     * string (minimal escapes): `"(?:[^"]|\\")*"`

I think the block comment is better like this:

`r"/(?:[^*]|\*[^/])*\*/"`

this way it can be used with the line comment, i haven't found a way to put priority in a skip yet

**Comment by elenakrittik** [comment] 2023-07-28 11:20
> * \p{XID_Start}\p{XID_Continue}*

Maybe that's intentional, but this regex does not match identifiers starting with underscore. I personally use `(\p{XID_Start}|_)\p{XID_Continue}*`.

**Comment by jeertmans** [comment] 2023-08-02 15:56
Hello @elenakrittik, do you know if `regex-syntax` supports that kind of regexes?

**Comment by elenakrittik** [comment] 2023-08-02 16:11
Not sure which "kind" are you referring to.. If you're talking about `\p`s then i think yes, because lexer tests (which include multiple languages and symbols, and combinations of them) i've written for the above-mentioned regex pass just fine.

**Comment by jeertmans** [comment] 2023-08-02 17:26
Can this be caused by the fact that we use a previous version of regex-syntax? Can you try using logos from #320?

**Comment by elenakrittik** [comment] 2023-08-10 11:43
Sorry for the delay.

Assuming this input:

```gd
someident
_someident
```

..this logos dependency:

```toml
logos = { git = "https://github.com/jeertmans/logos.git", branch = "bump-regex-syntax" }
```

..and this token definition:

```rs
    #[regex(r"\p{XID_Start}\p{XID_Continue}*")]
    Identifier(&'a str),
```

Running logos yields the following result (`parse` currently sorts all errors and token by their spans and then prints them in order):

```
    Running `target/debug/gdtk parse --file incremental.gd`
Identifier("someident")
Newline
error: Unknown character.
--> incremental.gd:10..11
Identifier("someident")
```

So it seems regex-syntax defers the job of transforming `\p`s to the actual regex "executor", and that "executor" mistakenly (or not?) does not count underscore as a valid XID_Start character.

**Comment by jeertmans** [comment] 2023-08-10 12:10
That's definitely a bug because executing the following code

```rust
use regex_syntax::parse;

fn main() {
    let regex = r"(\p{XID_Start}|_)\p{XID_Continue}*";
    let hir = parse(regex).unwrap();
    
    println!("{hir:#?}");
}
```
on the [rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4981e9a663525e5aef8b11043668f322) yields a seemingly correct HIR, which is used to construct Logo's MIR.

**Comment by elenakrittik** [comment] 2023-08-10 15:09
Perhaps you wanted to test the original regex? In your snippet you're using an alternation to include underscore, but parsing `\p{XID_Start}` by itself still does not emit underscore as far as i can tell. (so maybe that *is* a bug, but in regex-syntax and not logos?)

**Comment by jeertmans** [comment] 2023-08-10 15:26
Oh yeah, I didn't notice `...|_)` was actually a fix.

But are you sure `XID_Start` includes the underscore? I cannot see that anywhere on https://unicode.org/reports/tr31/#Table_Lexical_Classes_for_Identifiers.

For example, the `unicode-ident` crate, specialized for `XID_Start` and `XID_Continue`, returns `false` when checking if `_` matches `XID_Start`.

```rust
use unicode_ident::*;

fn main() {
    let b = is_xid_start('_');
    
    println!("{b}");
}
```

See [rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=82c1803dc5cec697d45fd2e466762192).

**Comment by elenakrittik** [comment] 2023-08-10 16:00
> mistakenly (***or not?***)

I were not sure whether this is an intended behaviour or a bug in any library in the supply chain. With your comment it seems like underscore indeed is not part of the `XID_Start` group (which feels strange, since most, if not all, languages allow identifiers to start with underscore). Due to the reason inside parentheses, i think it will be right to ask @CAD97 to edit their regex to include underscore alternation so that less people coming across this thread fall into this trap.

**Comment by jeertmans** [comment] 2023-08-10 20:18
Well maybe it’s worth creating an issue on the regex-syntax crate :)
But if that’s handwritten in the Unicode rules, I don’t think that will ever change 😅

**Comment by CAD97** [comment] 2023-08-10 20:24
[Unicode® Standard Annex #31 UNICODE IDENTIFIER AND PATTERN SYNTAX](https://unicode.org/reports/tr31/) §2.4 [Specific Character Adjustments](https://unicode.org/reports/tr31/#Specific_Character_Adjustments) calls `_` out specifically for being XID_Continue but not XID_Start, but commonly included into the Start class for identifiers, as well as in §1.2 [Customization](https://unicode.org/reports/tr31/#Customization). Representing the *Rust* identifier syntax it is of course correct to include `_` in Start. But for generic identifier syntax, it is better to use the unmodified character classes and point at UAX#31 such that language designers can make an informed decision. Implementors of an existing grammar are expected to know what the grammar they're implementing calls for.

**Comment by jeertmans** [comment] 2024-02-13 09:31
Closing this as I feel this is now documented in the handbook. If needed, feel free to re-open this issue!

**Closed by jeertmans** 2024-02-13 09:31 UTC
Labels: meta, book

**Comment by andrewbaxter** [comment] 2024-12-31 08:14
Where is this in the handbook? I'd have guessed https://logos.maciej.codes/common-regex.html but that doesn't seem to have any of the above common regexes.

**Comment by jeertmans** [comment] 2024-12-31 09:16
> Where is this in the handbook? I'd have guessed https://logos.maciej.codes/common-regex.html but that doesn't seem to have any of the above common regexes.

Look at the examples instead, see https://logos.maciej.codes/examples.html.
