### ISSUE TITLE
Logos skipping first token

### ISSUE THREAD

**Issue by Amanita-muscaria** [maciejhirsz/logos#83] opened 2019-08-17 20:19 UTC
I'm reading data into a string from a file and passing that to my lexer but it keeps skipping the token at the beginning of the file. It does not seem to matter which token it is.

These are those that I have defined.

```Rust
#[derive(Logos, Debug, PartialEq, Clone, Copy)]
enum DTToken {
    #[end]
    End,
    #[error]
    Error,

    #[token = "{"]
    NodeStart,
    #[token = "};"]
    NodeEnd,
    #[token = "="]
    Equals,
    #[token = ";"]
    StatementEnd,
    #[token = "/"]
    Directive,
    #[token = "//"]
    LineComment,
    #[token = "/*"]
    BlockCommentStart,
    #[token = "*/"]
    BlockCommentEnd,
    #[token = "\n"]
    NewLine,

    #[regex = r#"(#include)|(/include/)"#]
    Include,
    #[token = "#define"]
    Define,

    #[regex = r#"[#[:alnum:]_@<>,./"-]+"#]
    Text,
    #[regex = r#"\s"#]
    WhiteSpace
}
```

These are the first couple lines from the file in question
```
/*
asdfasdfasdf
*/
/dts-v1/;

/*
asdfasdf
*/
```
It doesn't matter if I have the /dts-v1/; or the nonsensical block comment, it will always first return the second symbol of the file.

**Comment by maciejhirsz** [comment] 2019-08-26 12:36
Do you call `advance` before reading the token? The lexer will read the first token when it's constructed, so if you call `advance` before reading you will skip the first token.

**Comment by Amanita-muscaria** [comment] 2019-08-26 12:50
I read the whole file into a string, pass it to logos and then use advance.

**Comment by maciejhirsz** [comment] 2019-08-26 15:31
Can you post a snippet of the code? To reiterate what I'm trying to explain, the example from read me:

```rust
    let mut lexer = Token::lexer("Create ridiculously fast Lexers.");

    // Not calling `advance` yet, the first token has already been read

    assert_eq!(lexer.token, Token::Text);
    assert_eq!(lexer.slice(), "Create");
    assert_eq!(lexer.range(), 0..6);

    // First advance moves us to the second token
    lexer.advance();

    assert_eq!(lexer.token, Token::Text);
    assert_eq!(lexer.slice(), "ridiculously");
    assert_eq!(lexer.range(), 7..19);
```

**Comment by maciejhirsz** [comment] 2019-08-28 15:31
Ye, [you are calling `advance` first thing in a loop](https://github.com/Amanita-muscaria/mimir/blob/e4c83ebd44fd3cd641bfe3c0cbfbdd8b9d2f5f8b/src/dt_lexer.rs#L77-L79), so that's why you are missing the first token.

Gonna close this as it's not an issue with Logos. It should be pretty easy to fix, you might have to store the return value in a variable, before calling advance at the end of the loop, not the beginning, good luck! :)

**Closed by maciejhirsz** 2019-08-28 15:31 UTC

**Comment by Amanita-muscaria** [comment] 2019-08-30 00:19
Wait, is there something else I should be doing [than what I'm doing in new()](https://github.com/Amanita-muscaria/mimir/blob/e4c83ebd44fd3cd641bfe3c0cbfbdd8b9d2f5f8b/src/dt_lexer.rs#L71)?

**Comment by maciejhirsz** [comment] 2019-09-03 14:55
No, that's fine. The problem is that as soon as you call `next` on `DTLexer`, the first thing that happens is `lex.advance()`. Given code:

```rust
impl<'a> DTLexer<'a> {
    pub fn new(data: &'a str) -> Self {
        DTLexer {
            lex: DTToken::lexer(data),
        }
    }
    pub fn next(&mut self) -> Result<DTInfo, DTError> {
        let lex = &mut self.lex;
        loop {
            lex.advance();
...
```

Then:

```rust
let dtlexer = DTLexer::new(&file_stack[0].1);

// at this point dtlexer.lex.token holds the first token

let second = lex.next()?; // This will be the second token because
                          // the first thing that happens inside `next`
                          // is calling `advance`.
```

You need to inverse the logic inside `next`, so that `lex.token` is checked _before_ `lex.advance()` is called.
